/**
 * The device key: vault encryption with nothing for the user to remember.
 *
 * A passphrase buys one thing — the key does not exist on disk, so a stolen
 * profile directory is inert. It costs the user a secret they must invent,
 * retype constantly, and cannot recover. For a tool whose whole point is that
 * you already have a password manager, that is a bad trade, and it is not the
 * trade the browser itself makes.
 *
 * So the default is a **non-extractable AES-256-GCM key** generated by
 * WebCrypto and stored in IndexedDB as a `CryptoKey` object, never as bytes.
 * What that buys:
 *
 *   - The raw key never exists in JavaScript. `extractable: false` means
 *     `exportKey` throws — for us and for anything that compromises us.
 *   - It is not in `chrome.storage`, so nothing that dumps extension storage
 *     (including our own debugging) ever sees it.
 *   - It cannot be copied out by a content script, a page, or another
 *     extension; IndexedDB is origin-scoped to this extension.
 *
 * What it does not buy, stated plainly: an attacker with **offline access to
 * the profile directory** can, with effort, recover it. Chrome's own password
 * store has the same property — on Linux it falls back to a fixed key when no
 * OS keyring is present. So this is not weaker than the browser you are running
 * it in, but it is weaker than a passphrase, and anyone who wants that stronger
 * property can turn it on in Settings.
 *
 * The real upgrade is the OS keychain via the optional bridge, which is where
 * this is heading.
 */

const DB_NAME = 'firesync-keys';
const DB_VERSION = 1;
const STORE = 'keys';
const KEY_ID = 'vault';

/**
 * Storage for the key object. Abstracted so the logic is testable without a
 * real IndexedDB, and so the OS-keychain backend can slot in later.
 */
export interface DeviceKeyStore {
  get(id: string): Promise<CryptoKey | undefined>;
  put(id: string, key: CryptoKey): Promise<void>;
  delete(id: string): Promise<void>;
}

/** IndexedDB-backed store — the real one. */
export class IndexedDbKeyStore implements DeviceKeyStore {
  private open(): Promise<IDBDatabase> {
    return new Promise((resolve, reject) => {
      const request = indexedDB.open(DB_NAME, DB_VERSION);
      request.onupgradeneeded = () => {
        if (!request.result.objectStoreNames.contains(STORE)) {
          request.result.createObjectStore(STORE);
        }
      };
      request.onsuccess = () => resolve(request.result);
      request.onerror = () => reject(request.error ?? new Error('could not open the key store'));
    });
  }

  private async transact<T>(
    mode: IDBTransactionMode,
    run: (store: IDBObjectStore) => IDBRequest<T>,
  ): Promise<T> {
    const db = await this.open();
    try {
      return await new Promise<T>((resolve, reject) => {
        const tx = db.transaction(STORE, mode);
        const request = run(tx.objectStore(STORE));
        request.onsuccess = () => resolve(request.result);
        request.onerror = () => reject(request.error ?? new Error('key store request failed'));
        tx.onabort = () => reject(tx.error ?? new Error('key store transaction aborted'));
      });
    } finally {
      db.close();
    }
  }

  async get(id: string): Promise<CryptoKey | undefined> {
    return this.transact('readonly', (store) => store.get(id) as IDBRequest<CryptoKey | undefined>);
  }

  async put(id: string, key: CryptoKey): Promise<void> {
    await this.transact('readwrite', (store) => store.put(key, id) as IDBRequest<IDBValidKey>);
  }

  async delete(id: string): Promise<void> {
    await this.transact('readwrite', (store) => store.delete(id) as IDBRequest<undefined>);
  }
}

/** In-memory store, for tests. */
export class MemoryKeyStore implements DeviceKeyStore {
  private readonly map = new Map<string, CryptoKey>();

  async get(id: string): Promise<CryptoKey | undefined> {
    return this.map.get(id);
  }

  async put(id: string, key: CryptoKey): Promise<void> {
    this.map.set(id, key);
  }

  async delete(id: string): Promise<void> {
    this.map.delete(id);
  }
}

/** Mint a fresh AES-256-GCM key that can never be exported. */
export async function generateDeviceKey(): Promise<CryptoKey> {
  return crypto.subtle.generateKey({ name: 'AES-GCM', length: 256 }, false, [
    'encrypt',
    'decrypt',
  ]);
}

/**
 * The vault key for this device, creating it on first use.
 *
 * Idempotent: a second call returns the same key, which is what makes the vault
 * readable across service-worker restarts without anything being remembered.
 */
export async function getOrCreateDeviceKey(store: DeviceKeyStore): Promise<CryptoKey> {
  const existing = await store.get(KEY_ID);
  if (existing) return existing;

  const key = await generateDeviceKey();
  await store.put(KEY_ID, key);

  // Read it back: if the platform silently failed to persist a non-extractable
  // key, every future launch would mint a new one and the vault would be
  // unreadable. Better to find out now.
  const confirmed = await store.get(KEY_ID);
  if (!confirmed) {
    throw new Error('the device key could not be stored; the vault cannot be protected');
  }
  return confirmed;
}

export async function hasDeviceKey(store: DeviceKeyStore): Promise<boolean> {
  return (await store.get(KEY_ID)) !== undefined;
}

export async function clearDeviceKey(store: DeviceKeyStore): Promise<void> {
  await store.delete(KEY_ID);
}

/** The store used in the extension. Swapped out in tests. */
export const deviceKeyStore: DeviceKeyStore = /* @__PURE__ */ (() =>
  typeof indexedDB === 'undefined' ? new MemoryKeyStore() : new IndexedDbKeyStore())();
