#!/usr/bin/env node
/**
 * Regenerate `src/match/psl-generated.ts` from publicsuffix.org.
 *
 * The bundled list in `src/match/psl.ts` is a hand-curated subset that keeps
 * the extension small and the tests offline. Run this when you want complete
 * coverage; `psl.ts` prefers the generated data when it is present.
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const SOURCE = 'https://publicsuffix.org/list/public_suffix_list.dat';
const root = dirname(dirname(fileURLToPath(import.meta.url)));
const out = join(root, 'src/match/psl-generated.ts');

const response = await fetch(SOURCE);
if (!response.ok) {
  console.error(`could not fetch the public suffix list: ${response.status}`);
  process.exit(1);
}

const suffixes = [];
const wildcards = [];
const exceptions = [];

for (const raw of (await response.text()).split('\n')) {
  const line = raw.trim();
  if (!line || line.startsWith('//')) continue;
  if (line.startsWith('!')) exceptions.push(line.slice(1));
  else if (line.startsWith('*.')) wildcards.push(line.slice(2));
  else if (line.includes('.')) suffixes.push(line);
}

const serialize = (values) =>
  `[\n${values
    .sort()
    .map((value) => `  ${JSON.stringify(value)},`)
    .join('\n')}\n]`;

mkdirSync(dirname(out), { recursive: true });
writeFileSync(
  out,
  `// Generated by scripts/fetch-psl.mjs from ${SOURCE}
// Do not edit by hand.

export const GENERATED_PUBLIC_SUFFIXES: readonly string[] = ${serialize(suffixes)};

export const GENERATED_WILDCARD_SUFFIXES: readonly string[] = ${serialize(wildcards)};

export const GENERATED_SUFFIX_EXCEPTIONS: readonly string[] = ${serialize(exceptions)};
`,
);

console.log(
  `wrote ${out}\n  ${suffixes.length} suffixes, ${wildcards.length} wildcards, ${exceptions.length} exceptions`,
);
